export const api = {
	login: '&r=member.login.wxapp_authorization_code',
	memberIndex: '&r=member.index',
	NavbarList: '&r=common.nav',
	likeList: '&r=goods.index.youlike',
	followList: '&r=member.favorite.get_list',
	traceList: '&r=member.history.get_list',
	menuList: '&r=common.menu',
	addressList: '&r=member.address',
	defaultAddress: '&r=member.address.setdefault',
	delAddress: '&r=member.address.delete',
	editAddress: '&r=member.address.submit',
	getMemberInfo: '&r=member.member_info',
	getGoodsInfo: '&r=goods.detail',
	search: '&r=goods.index.query',
	interestList: '&r=member.group.get_group',
	saveInterest: '&r=member.group.save',
	plusDetail: '&r=plus.detail',
	sendCode: '&r=util.common.send_code',
	saveFillData: '&r=plus.member_info',
	buyPlus: '&r=plus.buy_plus',
	payPlus: '&r=plus.payinfo',
	category: '&r=goods.category',
	initInfo: '&r=member.member_info.save',
	newUserCoupon: '&r=newbee_coupon',
	getNewCoupon: '&r=newbee_coupon.get_newbee_coupon',
	getCouponList: '&r=sale.coupon.my.coupon_list',
	getRechargeInfo: '&r=member.recharge',
	rechargeSubmit: '&r=member.recharge.submit',
	couponDescription: '&r=newbee_coupon.description',
	goodsOptions: '&r=goods.picker',
	pushCart: '&r=member.cart.add',
	myCart: '&r=member.cart.get_list',
	goodsChoice: '&r=member.cart.select',
	changeCount: '&r=member.cart.update',
	orderPreview: '&r=order.view',
	orderSubmit: '&r=order.add',
	orderPay: '&r=order.pay',
	cartRemove: '&r=member.cart.remove',
	collectGoods: '&r=member.cart.tofavorite',
	collectList: '&r=member.favorite.get_list',
	getAddressInfo: '&r=member.address.post',
	getOrderList: '&r=order.list.get_list',
	orderDetail: '&r=order.list.detail',
	cancelPay: '&r=order.op.cancel',
	finishOrder: '&r=order.op.finish',
	getRedPackets: '&r=redpackets',
	getGiftDetail: '&r=order.gift.detail',
	getGiftMySelf: '&r=order.gift.self_get',
	getGift: '&r=order.gift.get_gift',
	getGiftSuccess: '&r=order.gift.success',
	H5Login: '&r=member.login.authorization_code',
	index: '&r=index.index',
	test: '&r=index.index.test',
	discount: '&r=seckill',
	bargainIndex: '&r=bargain_v2',
	bargainList: '&r=bargain_v2.getList',
	myBargain: '&r=bargain_v2.myPost',
	bargainDetail: '&r=bargain_v2.detail',
	bargainLog: '&r=bargain_v2.log',
	index: '&r=index.index',
	test: '&r=index.index.test',
	pointsMall: '&r=creditshop',
	creditShopList: '&r=creditshop.lists.getlist',
	creditShopDetail: '&r=creditshop.detail',
	creditCreat: '&r=creditshop.create',
	creditPay: '&r=creditshop.pay',
	creditGetList: '&r=creditshop.creditLog',
	creditshopLogGetlist: '&r=creditshop.logList',
	creditGoodsOption: '&r=creditshop.option',
	groupsIndex: '&r=groups',
	discountIndexGoods: '&r=seckill.get_goods',
	searchGroups: '&r=groups.category.get_list',
	groupsDetail: '&r=groups.goods',
	groupsRecommend: '&r=groups.goods.other_team',
	setGroups: '&r=groups.orders.confirm',  //拼团订单预览、下单
	teamDetail: '&r=groups.team.detail',
	myGroups: '&r=groups.team.get_list',
	groupsIndex: '&r=groups',
	discountIndexGoods: '&r=seckill.get_goods',
	searchGroups: '&r=groups.category.get_list',
	groupsRecommend: '&r=groups.goods.other_team',
	myGroups: '&r=groups.team.get_list',
	discoverIndex: '&r=discover',  //发现首页
	discoverNew: '&r=discover.todayNew',  //发现上新
	disRecommendList: '&r=discover.recommend_list',  //今日推荐商品列表
	disRecommendBanner: '&r=discover.recommend',  //今日推荐banner
	disVideoList: '&r=discover.video',  //发现视频列表
	disVideoDetail: '&r=discover.video_detail',  //发现视频详情
	creditShopDetailPay: '&r=creditshop.detail.pay',
	creditShopLogDetail: '&r=creditshop.logDetail',
	signIndex: '&r=sign', //签到首页
	signIn: '&r=sign.dosign', //签到
	signRemind: '&r=sign.remind', //签到通知
	speakList: '&r=discover.speak_list', //达人说列表
	marketing: '&r=marketing', //xy营销
	addprice: '&r=addprice', //xy营销
	getCommentList: '&r=order.comment',  //评价的商品列表
	submitComment: '&r=order.comment.submit',  //提交商品评价
	groupsPay: '&r=groups.pay',  //拼团支付
	distribution: '&r=distribution', // 分销中心,
	abonus: '&r=distribution.index.abonus', // 分销佣金首页
	commissionOrder: '&r=distribution.commission_order',//分销订单接口
	distributionOrderList: '&r=distribution.order_list',// 分销订单分类查询
	chooseCoupon: '&r=sale.coupon.my.order_coupon', //下单时选择优惠券
	couponCenter: '&r=sale.coupon.getlist', //领券中心优惠券列表
	distributionMyTeam: '&r=distribution.my_team', // 分销我的团队接口
	distributionTeamList: '&r=distribution.team_list',// 我的团队列表
	distributionAbonusAbonusList: '&r=distribution.abonus.abonus_list',// 提现接口类型
	distributionAbonusGetList: '&r=distribution.abonus.get_list', // 提现列表
	distributionAbonusDetail: '&r=distribution.abonus.detail', // 提现详情接口
	distributionAbonus: '&r=distribution.abonus',// 提现方式接口
	cancelMyFollow: '&r=member.favorite.remove', //移除我的关注中的商品
	myRecord: '&r=member.history.get_list', //我的历史足迹
	myRecordRemove: '&r=member.history.remove', //删除我的历史足迹
	editUserInfo: '&r=member.member_info.update', //修改个人资料
	categoryList: '&r=goods.category.cate_list', //商品分类列表
	brandDetail: '&r=goods.category.brand_detail', // 品牌详情
	brandGoodsList: '&r=goods.category.getlist', // 品牌详情商品列表
	distributionAbonusWithdraw: '&r=distribution.abonus.withdraw',// 提交体检数据
	AbonusStoreList: '&r=distribution.abonus.store_list', // 门店列表接口
	IndexQrcode: '&r=distribution.index.qrcode', // 分销海报
	uploadImg: '&do=api&r=util.uploader',// 上传图片接口
	moodList: '&r=mood', // 心情列表
	chooseMood: '&r=mood.member_mood_log', // 选择心情
	moodDetail: '&r=mood.get_mood', // 心情详情
	checkMood: '&r=mood.check_mood_log', // 是否已选择今日心情
	searchHistory: '&r=goods.query_history', // 历史搜索记录
	clearHistory: '&r=goods.deleted_history', // 删除历史搜索记录
	certification: '&r=member.member_info.identity', // 实名认证
	logistics: '&r=order.list.express', // 物流
	checkOldMobile: '&r=member.member_info.check_old_mobile', // 验证旧的手机号码
	reBindMobile: '&r=member.member_info.rebind_mobile', // 绑定新的手机号码
	videoLike: '&r=discover.video_like', // 视频点赞
	checkOldMobile: '&r=member.member_info.check_old_mobile', // 验证就得手机号码
	creditshopLogExpress: '&r=creditshop.log.express', // 积分商城兑换订单物流
	groupsOrderList: '&r=groups.orders.get_list', //拼团订单列表
	groupsOrderDetail: '&r=groups.orders.detail', //拼团订单详情
	groupsOrderCancel: '&r=groups.orders.cancel', //取消拼团订单
	groupsOrderFinish: '&r=groups.orders.finish', //收货拼团订单
	getTeamId: '&r=groups.team.getTeamId', //订单id获取团id
	groupsOrderLogistics: '&r=groups.orders.express', //拼团订单物流
	getRules: '&r=util.common.rules', //获取各种规则、协议
	articleDetail: '&r=discover.art_detail', //文章详情
	articleLike: '&r=distribution.index.like_art', //文章点赞
	bindParent: '&r=distribution.index.check_agentid', //绑定关系
	seckillbooking: '&r=seckill.booking', //秒杀商品预约
	buyCoupon: '&r=sale.coupon.detail.pay', //领券中心领取优惠券
	checkLabel: '&r=member.index.check_label', //获取用户是否已填写初始化信息
	evaluateCategory: '&r=goods.detail.get_comments', //获取商品评论标签（好中差）
	getEvaluateList: '&r=goods.detail.get_comment_list', //获取商品评论列表
	couponCenterShare: '&r=common.share.couponCenter', //领券中心分享接口
	seckillShare: '&r=seckill.index.seckill_share', //秒杀首页分享接口
	commonShare: '&r=common.share', //商城分享接口
	invoice: '&r=order.invoice', //发票
	invoiceSubmit: '&r=order.invoice.submit', //发票申请
	diypages: '&r=index.index.diypages', //店铺装修单页
	wxConfig: '&r=util.common.wxJsConfig', //公众号配置
	wxUpload: '&r=util.common.uploadWxImage', //h5上传图片接口
	distArticle: '&r=distribution.index.article_list', //分销文章接口
	refund: '&r=order.refund.refundView', //订单申请退款&预览
	refundGoodsList: '&r=order.refund.goodsList', //售后商品列表
	refundList: '&r=order.refund.refundList', //售后列表
	refundDetail: '&r=order.refund.refundDetail', //售后详情
	expressList: '&r=order.refund.expressList', //快递列表
	fillExpress: '&r=order.refund.fillExpress', //售后快递提交
	noticeList: '&r=member.news.get_list',
	noticeDetail: '&r=member.news.detail' ,

	// shopp
	selectUserinfoByUserId: '/userinfo/selectUserinfoByUserId', // 用户等级查询
	setUpShop: '/wx/setUpShop',
	getOpenId: '/wx/getOpenId', // 获取openid
	payment:'/wx/wxPay',//支付
	noticeDetail: '&r=member.news.detail' ,
	getphone: '/business/getUnionid' ,
	getgzhopenid:'/wx/getGzCodeByDu',
	getopen:'/wx/getGzOpenid',
	getwxhypay:'/wx/H5Pay',
	gethuodong:'/img/selectImg',
	participation:'/conversion/participation', // 查看用户是否参与活动
	verifyCode:'/conversion/verifyCode', // 验证兑换码
	saveAdders:'/wx/saveAdders',// 开店保存地址
}
